export const wilayas = [
  'adrar',
  'chlef',
  'laghouat',
  'oum el bouaghi',
  'batna',
  'bédjaïa',
  'biskra',
  'béchar',
  'blida',
  'bouira',
  'tamanrassat',
  'tébessa',
  'tlemcen',
  'tiaret',
  'tizi ouzou',
  'alger',
  'djelfa',
  'jijel',
  'setif',
  'saïda',
  'skikda',
  'sidi bel abbès',
  'annaba',
  'guelma',
  'constantine',
  'médéa',
  'mostaganem',
  'm\'sila',
  'mascara',
  'ouregla',
  'oran',
  'el bayadh',
  'illizi',
  'bordj bou arreridj',
  'boumerdès',
  'el tarf',
  'tindouf',
  'tissemsit',
  'el oued',
  'khenchela',
  'souk ahras',
  'tipaza',
  'mila',
  'aïn defla',
  'naama',
  'aïn temouchent',
  'ghardaïa',
  'relizane'

];

export const niveaux = [
  'Sans objet',
   'Bac + 1',
   'Bac + 2',
   'Bac + 3 (License)',
   'Bac + 4',
   'Bac + 5 (Master)',
  'bac + 6',
  'bac + 7 (Doctorat)' ];

export const experiences = [
  'Aucune expérience',
  'Un an',
  'Deux ans',
  'Trois ans',
  'Quatre ans',
  'Cinq ans et plus'
]
export const domaines =[
  'techenique',
  'scientifique',
  'gestion',
];

export const diplomes =[
  'pas de diplome',
  ' informatique',
  ' mécanique',
  'comptabilité',
  'médecine',
  'médecine dentaire',
  'science pharmacetique',
  'science biologique',
  'electronique',
  'énergie renouvelable',
  'agro-alimentaire',
  'automatique',
  'marketing',
  'marketing digital',
  'linguistiques',
];
